name: ✨ Feature Request
description: Suggest an idea or enhancement for this project.
title: "[Feature]: "
labels: ["enhancement", "needs discussion"]
assignees:
  - jlouisbru # Assign to yourself, or leave blank
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest an idea! 
        Please describe your feature request with as much detail as possible.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting.
      options:
        - label: I have searched the existing [issues](https://github.com/jlouisbru/canvas-quiz-from-sheets/issues) to ensure this feature has not already been requested.
          required: true
        - label: I have considered whether this feature aligns with the general scope and purpose of the project.
          required: true

  - type: textarea
    id: problem-description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: "I'm always frustrated when [...] because [...]. It would be great if the script could also [...] to solve this."
    validations:
      required: true

  - type: textarea
    id: solution-description
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: "I would like the script to have a new option in 'CanvasQuiz_Config' called 'PUBLISH_QUIZ_IMMEDIATELY' (TRUE/FALSE). If TRUE, the quiz is published on Canvas after creation."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: "Alternatively, there could be a new menu item 'Publish Last Created Quiz'."
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, mockups, or screenshots about the feature request here.
      placeholder: "This would be particularly useful for users who..."
    validations:
      required: false

  - type: dropdown
    id: importance
    attributes:
      label: How important is this feature to you?
      description: This helps prioritize development.
      options:
        - Nice to Have
        - Important
        - Critical
    validations:
      required: false
